### ISSUE TITLE
MongoDB as backend example required

### ISSUE THREAD

**Issue by ChristophRh** [eclipse-basyx/basyx-java-examples#128]
I've been playing around with some examples of the OTS components using docker-compose.
Now I'm having trouble to get an example with MongoDB as backend to run.
I could not find an appropriate example in the repository, is there any?

Could you please provide me a working example of a docker-compose file starting the AAS-Server (and the AAS-Registry) with MongoDB as backend?

Thank You!

**Comment by ChristophRh** [comment]
Thank you very much for the example!

I think there is a hidden typo in the compose.yaml file:
https://github.com/eclipse-basyx/basyx-java-examples/blob/8b1404ebef1da375f1acd1e561ed850ace6621b7/basyx.docker/mongodb-deployment/compose.yaml#L14C35-L14C35

**Comment by FrankSchnicke** [comment]
You're right - thank you very much for pointing this out!
