### ISSUE TITLE
Examples for new AAS v3 components

### ISSUE THREAD

**Issue by mm-mse** [eclipse-basyx/basyx-java-examples#160]
It would be great to have docker-compose examples how to use the new components based on AAS v3 spec. Especially with the new UI that was recently released.

**Comment by FrankSchnicke** [comment]
We're hosting everything related to BaSyx V2 in the [basyx-java-server-sdk Repo](https://github.com/eclipse-basyx/basyx-java-server-sdk). There, you will find exactly what you're looking for in the examples folder
