### ISSUE TITLE
simple deployment with gui stuck in spinner 

### ISSUE THREAD

**Issue by yousifBilal** [eclipse-basyx/basyx-java-examples#40]
Opening the AAS of the given example does not work. Results in "CORS header ‘Access-Control-Allow-Origin’ missing".

Managed to solve it by adding "- basyxcontext_accesscontrolalloworigin=http://localhost:8080" to the [environment of aas](https://github.com/eclipse-basyx/basyx-java-examples/blob/619a6fbdb68511229aa199b45a2bf36ed0f8ad61/basyx.docker/simple-deployment-with-gui/compose.yaml#L18)

**Comment by FrankSchnicke** [comment]
Thanks for pointing this out. Right, the CORS header needs to be configured.
