### ISSUE TITLE
Uploaded aasx file content invisible in registry

### ISSUE THREAD

**Issue by kozmad** [eclipse-basyx/basyx-java-examples#63]
Dear developers, 

At first, I'd like to thank you for developing this great ecosystem.

I've checked out the provided [docker-compose.yaml](https://github.com/eclipse-basyx/basyx-java-examples/blob/main/basyx.docker/simple-deployment-with-gui/compose.yaml) example and it worked like a charm.

After I changed the default settings of aas.source=aasx/01_Festo.aasx to empty and aasxUpload to Enabled. (I've tried to define these values with environment variables and propoerty files as well.) The docker-compose was restarted.

For uploading an example aasx file, I used the following command:
```curl.exe --verbose --request POST  --form "someKey=@14_Siemens.aasx"  http://localhost:4001/aasServer/shells/aasx```

After executing the command above, the uploaded content can be found on page http://localhost:4001/aasServer/shells, but the registry is not able to detect this change somehow, so http://localhost:4000/registry/api/v1/registry page remains empty, and the GUI page cannot retrieve data from the registry to display the uploaded data structure.

Interestingly, if I set up the infrastructure with MQTT, MongoDB (c.f. attached file [aas.zip](https://github.com/eclipse-basyx/basyx-java-examples/files/10509400/aas.zip)), starting docker-compose, upload file with curl and after restarting aas-server and aas-registry makes the previuosly uploaded aasx file visible in the registry, so in the GUI as well.

```
>>>>$ docker-compose up -d mosquitto mongo mongo-express aas_gui 
[+] Running 5/5
 ⠿ Network industry_4_0_default  Created                                                                                                         0.8s
 ⠿ Container mongo_express       Started                                                                                                         3.0s
 ⠿ Container mosquitto           Started                                                                                                         3.7s
 ⠿ Container aas_gui             Started                                                                                                         2.6s
 ⠿ Container mongodb             Started                                                                                                         2.5s

>>>>$ docker-compose up -d registry  aas_server
[+] Running 2/2
 ⠿ Container aas_registry  Started                                                                                                               2.0s
 ⠿ Container aas_server    Started                                                                                                               1.7s

>>>>$ curl --verbose --request POST  \ 
     --form "someKey=@aas_samples/14_Siemens.aasx" \
     http://localhost:4001/aasServer/shells/aasx

>>>>$ docker-compose stop  registry  aas_server
[+] Running 2/2
 ⠿ Container aas_server    Stopped                                                                                                              10.8s
 ⠿ Container aas_registry  Stopped                                                                                                              10.6s

>>>>$ docker-compose up -d registry  aas_server
[+] Running 2/2
 ⠿ Container aas_server    Started                                                                                                               1.5s
 ⠿ Container aas_registry  Started                               

````

So, it seems aas-server or aas-register checks the database only at initialization or I've misconfigured something so aas-register is not informed about the changes.

Could you give me some hint, what could be the problem here?
 
Thank you for your help in advance!

Best regards,
Daniel

**Comment by FrankSchnicke** [comment]
Dear Daniel,

many thanks for the detailed description. The AASX Upload Endpoint does only add the AAS/Submodels of the AASX to the AAS Server - it does not automatically register them with the AAS Registry. While this is a feature that we're planning for a future release, right now you have to register the AAS/Submodels yourself.

The behaviour with MongoDB is explained by the AAS Server scanning the DB on startup and registering everything contained.

**Comment by FrankSchnicke** [comment]
This was implemented with https://github.com/eclipse-basyx/basyx-java-components/pull/258 and will be included in the next release end of March

**Comment by FrankSchnicke** [comment]
Hi, 

since this issue is closed, would it be possible to create a new issue with above description? This allows us to track the tasks more nicely.

Best regards,
Frank
